引上げ権限までのマニュアル作成
atled-workflow/AgileWorks-doc pull request #2
Opened 2024-11-18 00:36 UTC by Seiya-Ito-atled

2024-11-19 01:06 UTC, masataka-tani commented
> スキーマで、typeをarrayにしてitemsで中身を記述していますが、html表示するとitemsも入ってしまいます。
> 画像のxpのようにするにはどう設定すればいいでしょうか。

OpenAPIドキュメントのバージョンが3.1.0の場合は`Items`も入るようです。
ドキュメントの書き方としては合っていますのでこのままでもいいと思います。
（X-pointのOpenAPIドキュメントは3.0.3のため`Items`が入っていません。）

2024-11-19 06:21 UTC, masataka-tani requested changes
レビューが完了しましたのでコメントをご確認ください。

PDFマニュアルとOpenAPIドキュメントの差異を指摘したコメントについては、
PDFマニュアルの内容が正しいのかどうかを確認してから対応をお願いいたします。
（PDFマニュアルの記載内容が誤っていてOpenAPIドキュメントが正しいのであれば修正なし）

2024-11-19 06:21 UTC, masataka-tani commented on openapi.yaml
> +          examples:
◯◯作成API、◯◯更新API、◯◯適用終了APIの3種類は同じレスポンス構成で返されると思います。
Example Object も`$ref`による再利用ができますので、components/examplesに上記3つのAPIの共通exampleを定義して、参照する形にしてみてください。（リクエストのexampleについても共通化できればしてみてください。)
ファイルサイズが削減されて今後yamlファイルが編集しやすくなると思います。
参考：https://swagger.io/specification/#example-object

2024-11-26 04:45 UTC, Seiya-Ito-atled commented on openapi.yaml
> +  /WebApi/Service?name=org.Org&method=dleteUnitAppointment:
修正しました。

2024-11-26 04:46 UTC, Seiya-Ito-atled commented on openapi.yaml
> +              - proxyUserCode
実際は principalUserCode, proxyUserCodeになります。

2024-11-26 04:51 UTC, Seiya-Ito-atled commented on openapi.yaml
> +        application/json:
実際は必須ではありません。

2024-11-26 04:51 UTC, Seiya-Ito-atled commented on openapi.yaml
> +          schema:
実際は必須ではありません。

2024-11-26 04:52 UTC, Seiya-Ito-atled commented on openapi.yaml
> +                  *「代理申請承認API」または「代理申請承認API」で取得した値を指定
はい。修正しました。

2024-11-26 04:53 UTC, Seiya-Ito-atled commented on openapi.yaml
> +            type: object
実際は id, principalUserCode, proxyUserCodeになります。

2024-11-26 04:54 UTC, Seiya-Ito-atled commented on openapi.yaml
> +          schema:
実際は必須ではありません。

2024-11-26 04:54 UTC, Seiya-Ito-atled commented on openapi.yaml
> +                  *「権限委譲承認API」または「権限委譲承認API」で取得した値を指定
はい。修正しました。

2024-11-26 04:55 UTC, Seiya-Ito-atled commented on openapi.yaml
> +              - toUserCode
実際は id, fromUserCode, toUserCodeになります。

2024-11-26 04:57 UTC, Seiya-Ito-atled commented on openapi.yaml
> +              - userCode
実際は userCode のみになります。

2024-11-26 04:59 UTC, Seiya-Ito-atled commented on openapi.yaml
> +            allOf:
実際は必須項目はありません。

2024-11-26 04:59 UTC, Seiya-Ito-atled commented on openapi.yaml
> +              - userCode
実際は id, userCode なります。

2024-11-26 05:00 UTC, Seiya-Ito-atled commented on openapi.yaml
> +                  *「引上げ権限承認API」または「引上げ権限承認API」で取得した値を指定
はい。修正しました。

2024-11-26 06:34 UTC, Seiya-Ito-atled commented on openapi.yaml
> +        |EQUAL|～と等しい|
修正しました。

2024-11-26 08:10 UTC, Seiya-Ito-atled commented on openapi.yaml
> +          examples:
パラメータが不正のレスポンスは定義したexampleを参照するようにしました。<br>
その他については、一部だけ定義を使って異なる部分はそれぞれ入力するのだろうと思ったのですが、うまくできませんでした。

2024-11-27 07:49 UTC, masataka-tani commented on openapi.yaml
> +                  *「権限委譲承認API」または「権限委譲承認API」で取得した値を指定
> 「権限委譲作成API」または「権限委譲承認API」で取得した値を指定

「権限委譲承認API」ではなく、「権限委譲参照API」ではないですか？

2024-11-27 07:50 UTC, masataka-tani commented on openapi.yaml
> +                  *「引上げ権限承認API」または「引上げ権限承認API」で取得した値を指定
> 「引上げ権限作成API」または「引上げ権限承認API」で取得した値を指定

「引上げ権限承認API」ではなく、「引上げ権限参照API」ではないですか？

2024-11-29 01:46 UTC, Seiya-Ito-atled commented on openapi.yaml
> +                  *「代理申請承認API」または「代理申請承認API」で取得した値を指定
失礼いたしました。
修正しました。

2024-11-29 01:46 UTC, Seiya-Ito-atled commented on openapi.yaml
> +                  *「権限委譲承認API」または「権限委譲承認API」で取得した値を指定
失礼いたしました。
修正しました。

2024-11-29 01:47 UTC, Seiya-Ito-atled commented on openapi.yaml
> +                  *「引上げ権限承認API」または「引上げ権限承認API」で取得した値を指定
失礼いたしました。
修正しました。

2024-11-29 01:48 UTC, Seiya-Ito-atled commented on openapi.yaml
> +          examples:
> リクエストが不正のexampleの参照先が誤っているようで、エディタ上でエラーがでています。

修正しました。


> エディタは何を使っていますか？

サクラエディタを使っていました。


> dockerでNext Swagger Editorというエディタを使うとエラー箇所がわかるのでおすすめです。

ありがとうございます！

2024-11-29 08:18 UTC, masataka-tani requested changes
追加の指摘がありますのでご確認をお願いいたします。

2024-11-29 08:21 UTC, Seiya-Ito-atled commented on openapi.yaml
> +        代理申請を更新します。
修正しました。

2024-12-02 00:11 UTC, masataka-tani approved these changes
確認しました。
追加の指摘はありません。

2024-12-02 00:13 UTC, merged