プライベートロール作成～ユニバーサルロール適用終了までの説明作成
atled-workflow/AgileWorks-doc pull request #3
Opened 2024-12-04 01:57 UTC by Seiya-Ito-atled

2024-12-06 07:54 UTC, masataka-tani requested changes
レビューしました。
幾つかコメントしましたのでご確認ください。

2024-12-06 07:54 UTC, masataka-tani commented on openapi.yaml
> +                      |UNIT_CASCADE|ユーザー指定（下位含める）|
> ユーザー指定（下位含める）

組織指定（下位含める）ではないですか？

2024-12-06 07:54 UTC, masataka-tani commented on openapi.yaml
> +              - folderCode
プライベートロール更新API
リクエストボディのnameはPDFマニュアル上は必須項目ではありません。
OpenAPIドキュメントが正しければこの指摘は無視してください。

2024-12-06 07:54 UTC, masataka-tani commented on openapi.yaml
> +                type: date
今更の指摘となって申し訳ないですが、OpenAPIドキュメントはデータ型「date」をサポートしていないようです。（Swagger Editorでエラーになっています）
日付型のtypeはstringとして、patternでどういった形式の日付なのか定義した方が良いです。
(他に日付型の定義でいい方法があればその方法で構いません。）

[参考](https://zenn.dev/shimakaze_soft/scraps/720776a518b32b#:~:text=%E3%83%9F%E3%83%AA%E7%A7%92%E7%B2%BE%E5%BA%A6%EF%BC%88YYYY%2DMM%2DDDThh%3Amm%3Ass.sss%2BTZD%EF%BC%89%E3%81%AE%E5%A0%B4%E5%90%88)

2024-12-06 08:08 UTC, Seiya-Ito-atled commented on openapi.yaml
> +              - folderCode
実際は必須になります。

2024-12-06 08:08 UTC, Seiya-Ito-atled commented on openapi.yaml
> +                      |UNIT_CASCADE|ユーザー指定（下位含める）|
修正しました。

2024-12-06 08:33 UTC, Seiya-Ito-atled commented on openapi.yaml
> +                type: date
`pattern: ^((?:[1-9][0-9]*)?[0-9]{4})-(1[0-2]|0[1-9])-(3[01]|0[1-9]|[12][0-9]) (2[0-3]|[01][0-9]):([0-5][0-9]):([0-5][0-9]) ([A-Z]{3})$`
上記のようにしました。

2024-12-08 23:07 UTC, masataka-tani approved these changes
確認OKです。

2024-12-10 09:09 UTC, merged