共通, 書類API, ワークフローAPIの説明作成
atled-workflow/AgileWorks-doc pull request #4
Opened 2024-12-11 01:11 UTC by Seiya-Ito-atled

2024-12-12 02:04 UTC, Seiya-Ito-atled commented
パラメータ"model_model"で、「APIの各ページを参照」となっていますが、modelの説明を作ってませんでした。
`pattern: doc.DocHeaderResponseModel`のようにスキーマに追記します。

2024-12-16 01:22 UTC, masataka-tani requested changes
レビューしました。
コメントを確認して指摘対応をお願いいたします。

2024-12-16 01:22 UTC, masataka-tani commented on openapi.yaml
> +                    type: integer
登録フォーム一覧取得API
業務カテゴリ名称、業務カテゴリIDの説明は詳細設計書の内容を転記したものだと思われますが、詳細設計書の説明は開発者向けの補足情報に見えます。
AWの仕様について詳しくないのでこちらでは判断できませんが、上記2つのパラメータの説明はお客様がこのAPIを使用する際に必要な情報でしょうか？

・お客様がこのAPIを使用する際に必要な情報である
・お客様に非公開のAPIで社内でのみ使用するAPIである
といった場合はこのままでも良いと思います。

2024-12-16 01:22 UTC, masataka-tani commented on openapi.yaml
> +                    pattern: publication.PublicFolderListModel
publication.PublicFolderListModelが定義されていません。
詳細設計書にも記載されていないので、どのようなオブジェクトか確認して追記をお願いいたします。

2024-12-16 01:22 UTC, masataka-tani commented on openapi.yaml
> +            example: 999
SwaggerEditorで以下の警告が出ていました。
`property "example" is deprecated, use "examples" instead`

お手数ですが各所の**examle**を**examples**に修正をお願いいたします。

2024-12-16 01:57 UTC, Seiya-Ito-atled commented on openapi.yaml
> +        $ref: "#/components/requestBodies/docId"
設定しました。

2024-12-16 02:00 UTC, Seiya-Ito-atled commented on openapi.yaml
> +        adminNo:
追記しました。

2024-12-16 02:27 UTC, Seiya-Ito-atled commented on openapi.yaml
> +            logicalOperatorType:
追記しました。(doc..RelativeConditionModelの詳細は、Zaoraruの書類ID：114773)
また、exampleでrelativeConditionListの中身を追記しました。

2024-12-16 02:29 UTC, Seiya-Ito-atled commented on openapi.yaml
>          application/json:
`application/octet-stream`に修正しました。

2024-12-16 02:38 UTC, Seiya-Ito-atled commented on openapi.yaml
> +              type: string
追記しました。

2024-12-16 05:21 UTC, Seiya-Ito-atled commented on openapi.yaml
> +
> 書類添付情報追加API
> multipart/form-dataのschemaが定義されていません。
説明を追記しました。

> 添付書類タイプがファイルの場合、アップロードファイルは multipart/form-data の２つ目に設定します。
> の「multipart/form-dataの2つ目」とは何を指しているのでしょうか？
説明を追記したschemaのattachmentに記載しました。

2024-12-16 05:24 UTC, Seiya-Ito-atled commented on openapi.yaml
> +            指定可能な値<br>
修正しました。

2024-12-16 05:24 UTC, Seiya-Ito-atled commented on openapi.yaml
> +            |REMIND_EXIST|催促あり|
修正しました。

2024-12-16 05:29 UTC, Seiya-Ito-atled commented on openapi.yaml
> +            type: object
はい、必須ではありません。

2024-12-16 05:30 UTC, Seiya-Ito-atled commented on openapi.yaml
> +              - condition
docIdのみ必須になります。
修正しました。

2024-12-16 05:31 UTC, Seiya-Ito-atled commented on openapi.yaml
> +                      |READ|閲覧ステップ|
追記しました。

2024-12-16 05:37 UTC, Seiya-Ito-atled commented on openapi.yaml
> +              table:
追記しました。

2024-12-16 05:39 UTC, Seiya-Ito-atled commented on openapi.yaml
>          application/json:
`application/octet-stream`に修正しました。

2024-12-16 05:42 UTC, Seiya-Ito-atled commented on openapi.yaml
> +                    type: integer
不要なため削除しました。

2024-12-16 05:45 UTC, Seiya-Ito-atled commented on openapi.yaml
> +                    pattern: publication.PublicFolderListModel
`publication.PublicFolderInfoListModel`の間違いでした。
修正しました。

2024-12-16 06:03 UTC, Seiya-Ito-atled commented on openapi.yaml
> +            example: 999
`property "example" is deprecated, use "examples" instead`を確認できませんでした。
また、`example: 999`を`examples: 999`に変更するとexampleValueが0になりました。

2024-12-16 07:31 UTC, Seiya-Ito-atled commented on openapi.yaml
> +                  *FormMan
> contentに指定可能なのはsite.EnumBaseContentAccessType型のようなので、型を定義してください。

併せて、他にType型を定義していなかった箇所を修正しました。

> また、Example Valueのcontentは値が"string"になっています。
"FormMan"固定なのであればExample Valueに固定値として定義してください。

修正しました。

2024-12-16 08:44 UTC, masataka-tani commented on openapi.yaml
> +            logicalOperatorType:
doc.RelativeConditionModel＞userType
説明の「指定可能な値」がテーブルになっていないので、ヘッダ行とデータ行の間に|----|----|を追記してください。

2024-12-16 08:58 UTC, masataka-tani commented on openapi.yaml
> +            example: 999
失礼しました。
バージョンの違いですかね。。？
警告が出るだけで今の所影響は無いのでとりあえず無視しましょう。

2024-12-16 23:06 UTC, masataka-tani commented on openapi.yaml
> +
attachmentパラメータに「アップロードファイル名を指定します。」と記載がありますが、
アップロードファイル自体を指定ではないですか？
認識間違っていれば今のままで問題ありません。

2024-12-16 23:16 UTC, masataka-tani requested changes
追加のコメントがありますのでご確認ください。

2024-12-17 00:27 UTC, Seiya-Ito-atled commented on openapi.yaml
> +
入力ミスです。
修正しました。

2024-12-17 00:27 UTC, Seiya-Ito-atled commented on openapi.yaml
> +            logicalOperatorType:
修正しました。

2024-12-17 00:31 UTC, masataka-tani approved these changes
確認しました。追加のコメントはありません。

2024-12-17 05:11 UTC, merged